remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: jamemorr - technical blog
description: a technical blog focusing mainly on VCF content
navigation:
  - title: About
    url: /
  - title: Articles
    url: /articles
  - title: Series
    url: /series
linkedin_url: https://www.linkedin.com/in/jamemorr/
